language: c
compiler:
    - gcc
    - clang
before_install:
    - if [ "$CC" == "gcc" ]; then
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
          sudo apt-get update -qq;
      fi
install:
    - if [ "$CC" == "gcc" ]; then
          sudo apt-get install -qq gcc-4.8;
          export CC="gcc-4.8";
      fi
    - sudo apt-get install check
script: make test
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    format: html
    template:
      - "<a href='https://github.com/%{repository}'>%{repository}</a>#<a href='%{build_url}'>%{build_number}</a>: <code><a href='%{compare_url}'>%{commit}</a></code> on <code>%{branch}</code> by %{author} has <a href='%{build_url}'>%{result}</a>."
    rooms:
      secure: YCtUInhx74toFNey9E4V/5tbR1kGZqIBmn16l+Gmz5U+xba52pRPunegAqXZ1Ew8zA5+ppJb/BNugCiNtRWN/tZh/Er/hTV4zRwXJre3+gbHjzTS8QnALrl7fWPFKe5C1QMHdRHv6crBQ471YZLxUO4Imu5bvTW5BFOnJhVEuuI=
